### ISSUE TITLE
Remove package from PyPI

### ISSUE THREAD

**Issue by Zearin** [ralphbean/importlib_full#1]
Looks like this project is abandoned.

In the interest of making things less confusing for others who want `importlib` backports, please remove this package from PyPI, and mark the project as abandoned in the README.  

Thanks!

**Comment by ralphbean** [comment]
Yup.  Will do.  Thanks for the ping.

**Comment by ralphbean** [comment]
Huh.. can you remove packages from PyPI?  I don't see how to do it.

That aside, I've uploaded a new version that clearly indicates it is abandoned/deprecated.

**Comment by Zearin** [comment]
> I've uploaded a new version that clearly indicates it is abandoned/deprecated.

Awesome!  Thanks for the fast response. :)

> Huh.. can you remove packages from PyPI? I don't see how to do it.
1. Open https://pypi.python.org
2. Click “Login” from the box on the right
3. After logging in, the same box should now list your published packages
4. Click `importlib_full`

You should then be on a page to edit releases for that package.  You can use the checkboxes if you like, but if you scroll all the way to the bottom, there is a “Remove this package completely” option (colored in red).

**Comment by ralphbean** [comment]
Well I'll be.

Done!  Thanks :)

**Comment by Zearin** [comment]
:D :D :D
